# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/bills' do
  # This should return the minimal set of attributes required to create a valid
  # Bill. As you add validations to Bill, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { title: 'A Bill To Improve Something', congress: 119, number: 1234,
      original_chamber: 'house', type: 'hr', summary: 'A short summary.' }
  end

  let(:invalid_attributes) do
    { title: nil, congress: 119, number: 1234,
      original_chamber: 'house', type: 'hr', summary: 'A short summary.' }
  end

  describe 'GET /index' do
    before do
      stub_request(:get, /api\.congress\.gov/).to_return(
        status: 200,
        body: { bills: [] }.to_json,
        headers: { 'Content-Type' => 'application/json' }
      )
    end

    it 'renders a successful response' do
      Bill.create! valid_attributes
      get bills_url
      expect(response).to be_successful
    end
  end

  describe 'GET /index search' do
    let(:recent_bill) do
      { 'title' => 'A Recent Bill', 'congress' => 119, 'number' => 1, 'type' => 'HR' }
    end

    let(:filtered_bill) do
      { 'title' => 'A Filtered Bill', 'congress' => 119, 'number' => 2, 'type' => 'S' }
    end

    context 'with no search parameters' do
      it 'requests the most recent bills across all congresses' do
        stub_request(:get, 'https://api.congress.gov/v3/bill')
          .with(query: hash_including('limit' => '50'))
          .to_return(
            status: 200,
            body: { bills: [recent_bill] }.to_json,
            headers: { 'Content-Type' => 'application/json' }
          )

        get bills_url

        expect(response).to be_successful
        expect(response.body).to include('A Recent Bill')
      end
    end

    context 'with a congress and bill type' do
      it 'requests bills filtered to that congress and type' do
        stub_request(:get, 'https://api.congress.gov/v3/bill/119/s')
          .to_return(
            status: 200,
            body: { bills: [filtered_bill] }.to_json,
            headers: { 'Content-Type' => 'application/json' }
          )

        get bills_url, params: { congress: 119, type: 's' }

        expect(response).to be_successful
        expect(response.body).to include('A Filtered Bill')
      end
    end

    context 'with a bill type but no congress number' do
      it 'does not call the API and shows a validation message' do
        get bills_url, params: { type: 's' }

        expect(response).to be_successful
        expect(response.body).to include('Please provide a Congress number')
        expect(WebMock).not_to have_requested(:get, /api\.congress\.gov/)
      end
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      bill = Bill.create! valid_attributes
      get bill_url(bill)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_bill_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      bill = Bill.create! valid_attributes
      get edit_bill_url(bill)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Bill' do
        expect do
          post bills_url, params: { bill: valid_attributes }
        end.to change(Bill, :count).by(1)
      end

      it 'redirects to the created bill' do
        post bills_url, params: { bill: valid_attributes }
        expect(response).to redirect_to(bill_url(Bill.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Bill' do
        expect do
          post bills_url, params: { bill: invalid_attributes }
        end.not_to change(Bill, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post bills_url, params: { bill: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        { title: 'An Updated Bill Title' }
      end

      it 'updates the requested bill' do
        bill = Bill.create! valid_attributes
        patch bill_url(bill), params: { bill: new_attributes }
        bill.reload
        expect(bill.title).to eq('An Updated Bill Title')
      end

      it 'redirects to the bill' do
        bill = Bill.create! valid_attributes
        patch bill_url(bill), params: { bill: new_attributes }
        bill.reload
        expect(response).to redirect_to(bill_url(bill))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        bill = Bill.create! valid_attributes
        patch bill_url(bill), params: { bill: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested bill' do
      bill = Bill.create! valid_attributes
      expect do
        delete bill_url(bill)
      end.to change(Bill, :count).by(-1)
    end

    it 'redirects to the bills list' do
      bill = Bill.create! valid_attributes
      delete bill_url(bill)
      expect(response).to redirect_to(bills_url)
    end
  end
end
